export const GETPROVINCE='GETPROVINCE'

export const GETCITY='GETCITY'

export const LOGINSTATUS='LOGINSTATUS'

export const SAVEUSERINFO='SAVEUSERINFO'


export const GOTOUSERINFO='GOTOUSERINFO'

export const SAVECARNO='SAVECARNO'

export const SAVESCHEM='SAVESCHEM'

export const SAVEADDRESS='SAVEADDRESS'

export const SAVECHOICETYPE='SAVECHOICETYPE'

export const UPDATETYPE='UPDATETYPE'