module.exports = [
  { 
    alias: '/',
    path:'/pages/home/home',
    name:'Home',
    config:{
      navigationBarTitleText:'车碳宝',
    }
  },
  {
    path:'/pages/mydetail/detail',
    name:'detail',
    config:{
      navigationBarTitleText:'车碳宝',
     
    }
  },
  {
    path:'/pages/odometer/odometer',
    name:'odometer',
    config:{
      navigationBarTitleText:'拍照上传里程表'
    }
  },
  {
    path:'/pages/activity/activityFirst',
    name:"activityFirst",
    config:{
      navigationBarTitleText:"活动一:拍照参与减排"
    }
  },
  {
    path: '/pages/login/login',
    name:'Login',
    config: { // 页面配置，即 page.json 的内容
      navigationBarTitleText: '登录/注册',
   },
  },
  {
    path:'/pages/carplate/carplate',
    name:'carplate',
    config:{
      navigationBarTitleText:'输入车牌号码'
    }
  },
  {
    path:'/pages/login/bindphone',
    name:'bindphone',
    config:{
      navigationBarTitleText:"绑定手机"
    }
  },
  {
      path:'/pages/province/province',
      name:'province',
      config:{
        navigationBarTitleText:"选择省份"
      }
  },
  {
    path:'/pages/city/city',
    name:'city',
    config:{
      navigationBarTitleText:'选择市'
    } 
  },
  {
    path:'/pages/address/address',
    name:"address",
    config:{
      navigationBarTitleText:'填写设备邮寄地址'
    }
  },
  {
    path:'/pages/paymoney/index',
    name:'payMoney',
    config:{
      navigationBarTitleText:'押金付款确认'
    }
   },
  {
    path:'/pages/activity/activitySecond',
    name:'activitySecond',
    config:{
      navigationBarTitleText:"活动二:租赁车载wifi设备..."
    }
  },
  {
     path:'/pages/reward/reward',
     name:'reward',
     config:{
       navigationBarTitleText:'获得奖励',
      //  enablePullDownRefresh:true
     }
  },
  {
    path:'/pages/point/point',
    name:'point',
    config:{
      navigationBarTitleText:'碳积分',
      // enablePullDownRefresh:true
    }
  },
  {
    path:'/pages/carbonReduction/carbonReduction',
    name:'carbonReduction',
    config:{
      navigationBarTitleText:'减排达人',
      // enablePullDownRefresh:true,
    }
  },
  {
    path:'/pages/reduction/reduction',
    name:'reduction',
    config:{
      navigationBarTitleText:'选择减排计算方式'
    }
  },
  {
    path:'/pages/choicetype/choicetype',
    name:'choicetype',
    config:{
      navigationBarTitleText:'设备押金提交方式',
     
    }
  },
  {
    path:'/pages/terms/terms',
    name:'terms',
    config:{
      navigationBarTitleText:"用户协议"
    }
  }
 ]